prota/card/views.py
from prota import db
from flask import render_template, redirect,request,url_for,flash,abort, Blueprint
from prota.models import  User, Card, Score

# Views for Card Class #

card_blueprint = Blueprint('card',
                            __name__,
                            template_folder='templates/card')


@card_blueprint.route('view_all',methods=['GET','POST'])
def view_all():
    userid = request.args.get('userid', None)

    cardscore = db.session.query(Card, Score).join(Card).filter(userid == Score.userid)
    cards = Card.query.all()

    for item in cardscore:
        if item[0] in cards:
            cards.pop(cards.index(item[0]))

    return render_template('view_all.html',cards=cards,cardscore=cardscore)

prota/speedreview/views.py
from prota import db
from flask import render_template, redirect,request,url_for,flash,abort, Blueprint
from flask_login import login_required
from prota.models import  User, Card, update_score

# Views for speedview #

speedreview_blueprint = Blueprint('speedreview',
                            __name__,
                            template_folder='templates/speedreview')



@speedreview_blueprint.route('/game',methods=['GET','POST'])
@login_required
def game():
    cards = Card.query.all()
    return render_template('game.html',cards=cards)


# View for score screen (not currently implemented) #

@speedreview_blueprint.route('scorescreen',methods=['GET','POST'])
def scorescreen():
    form = request.form
    print(form[0])

    #print(type(cardid))
    # split = cardid.split(",")
    # idl = []
    # for item in split:
    #     idl.append(int(item))
    #
    # print(idl)

    return render_template('scorescreen.html')

# Old update view for updating a users score via a form #

# @speedreview_blueprint.route('updatescore',methods=['POST'])
# def updatescore():
#     form = request.form
#     cardid = int(form['cardid'])
#     userid = int(form['userid'])
#
#     update_score(userid,cardid)
#     print("success")
#     return ('', 204)
#
#

prota/users/views.py
from prota import app, db
from flask import render_template, redirect,request,url_for,flash,abort, Blueprint
from flask_login import login_user,login_required,logout_user
from prota.models import User
from prota.users.forms import LoginForm, RegistrationForm

# Views for User Class #

users_blueprint = Blueprint('users',
                            __name__,
                            template_folder='templates/users')



@users_blueprint.route('/welcome')
@login_required
def welcome_user():
    return render_template('welcome_user.html')

@users_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash("You logged out!")
    return redirect(url_for('index'))

@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if not user:
            flash("Email not registered")
        print("pas1")
        if user is not None and user.check_password(form.password.data):
            login_user(user)
            flash('Logged in Successfully!')

            next = request.args.get('next')

            if next == None or not next[0] == '/':
                next = url_for('users.welcome_user')

            return redirect(next)

    if form.email.data:
        flash("Please enter a valid email format")
    return render_template('login.html',form=form)

@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for registering! Now you can login!')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)

prota/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/base/base.css') }}">
      <meta charset="utf-8">
    <title>Prota</title>
  </head>
  <body>
  <ul class="nav">

  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('index') }}">Home</a>
  </li>
    {% if current_user.is_authenticated %}
    <li class="nav-link"><a href="{{ url_for('users.logout') }}">Log Out</a></li>
    {% else %}
    <li class="nav-link"><a href="{{ url_for('users.login') }}">Log In</a></li>
    <li class="nav-link"><a href="{{ url_for('users.register') }}">Register</a></li>
    {% endif %}

    <li class="nav-link"><a href="{{ url_for('card.view_all', userid=current_user.id) }}">Cards</a></li>
  <li class="nav-link"><a href="{{ url_for('speedreview.game') }}">Speed Review</a></li>







</ul>
  {% with messages = get_flashed_messages() %}
  {% if messages %}
    <ul class=flashes>
    {% for message in messages %}
      <li>{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}
{% block content %}

{% endblock %}

  </body>
</html>

prota/templates/home.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  {% if current_user.is_authenticated %}
    <p>Hi {{ current_user.username }}!</p>
  {% else %}
    <p>Please login or register!</p>
  {% endif %}
</div>

{% endblock %}

prota/templates/test.html
{% extends "base.html" %}
{% block content %}


<input type="button" class="button" value="play" onclick="play()">





<script type="text/javascript">
var t = "static/sounds/e.mp3"

function play(){
    var audio = new Audio(t);
    console.log(audio)
    audio.play();
}

</script>





{% endblock %}

prota/templates/testquiz.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="{{ url_for('static', filename='css/quiz.css') }}">

    <title>Hello, world!</title>
  </head>
  <body>




<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="row">
				<div class="col-md-3">
				</div>
				<div class="col-md-6">
          Translate
				</div>
				<div class="col-md-3">
				</div>
			</div>
			<div class="row">
				<div class="col-md-3">
				</div>
				<div class="col-md-6 lgntit ">
          <h1 class="text-center">English -> French</h1>
				</div>
				<div class="col-md-3">
				</div>
			</div>
			<div class="row">
				<div class="col-md-3">
				</div>
				<div class="col-md-6 boxmd">
					<h1 class="text-center" id="question">Question</h1>
					<div class="row">
						<div class="col-md-6 btnpad">
              <button type="button" class="button btn-block rounded-pill btntxt" id="btn1" onclick="check_answer('btn1')">---</button>
						</div>
						<div class="col-md-6 btnpad">
              <button type="button" class="button btn-block rounded-pill btntxt" id="btn2" onclick="check_answer('btn2')">---</button>
						</div>
					</div>
					<div class="row">
						<div class="col-md-6 btnpad">
              <button type="button" class="button btn-block rounded-pill btntxt" id="btn3" onclick="check_answer('btn3')">---</button>
						</div>
						<div class="col-md-6 btnpad">
              <button type="button" class="button btn-block rounded-pill btntxt" id="btn4" onclick="check_answer('btn4')">---</button>
						</div>
					</div>
				</div>
				<div class="col-md-3">
				</div>
			</div>
		</div>
	</div>
</div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  <script type="text/javascript">
	  var items = [
		{% for item in cards %}
			{
				sound:"{{item.fr_snd.split(',')[0]}}",
				fr:"{{item.fr}}",
				eng:"{{item.eng}}"
			},
		{% endfor %}
		];

	var maxcount = items.length;
	var count = 0;
	var answer = "";

	function genNum(limit){
		var arr = []
		while(arr.length < 4){
    	var r = Math.floor(Math.random()*limit) + 1;
    	if(arr.indexOf(r) === -1) arr.push(r);
		}
		return arr;
	}

	function new_question(count) {
		question.innerHTML = items[count].eng

		tmp = genNum(items.length-1)
		btn1.innerHTML = items[tmp[0]].fr
		btn2.innerHTML = items[tmp[1]].fr
		btn3.innerHTML = items[tmp[2]].fr
		btn4.innerHTML = items[tmp[3]].fr


		switch(genNum(4)[0]) {
			case 1:
			btn1.innerHTML = items[count].fr;
			answer = "btn1";
			break;
			case 2:
			btn2.innerHTML = items[count].fr ;
			answer = "btn2";
			break;
			case 3:
			btn3.innerHTML = items[count].fr;
			answer = "btn3";
			break;
			case 4:
			btn4.innerHTML = items[count].fr;
			answer = "btn4";
			break;

		}
	}

	function check_answer(choice) {
		if (choice == answer) {
			if (count < maxcount) {
				count +=1;
				new_question(count)
			}
		} else {
			window.alert("Wrong!")
		}
	}


	new_question(count)
  </script>

  </body>
</html>

prota/templates/testview.html
{% extends "base.html" %}
{% block content %}

<table>
  <tr>
    <th>French</th>
    <th>English</th>
  </tr>
  {% for card in cards %}
  <tr>
    <td>
    {% for line in card.fr_snd.split(',')  %}
    <input type="button" class="button" value="play" onclick="play('{{line}}')">
    {% endfor %}
    </td>
    <td>{{card.fr}}</td>
    <td><input type="button" class="button" value="play" onclick="play('{{card.eng_snd}}')"></td>
    <td>{{card.eng}}</td>


  </tr>
  {% endfor %}

</table>



<script type="text/javascript">

function play(loc){
    var audio = new Audio(loc);
    console.log(audio);
    audio.play();
}
</script>

{% endblock %}