prota/speedreview/views.py
from prota import db
from flask import render_template, redirect,request,url_for,flash,abort, Blueprint
from flask_login import login_required
from prota.models import  User, Card, update_score

# Views for speedview #

speedreview_blueprint = Blueprint('speedreview',
                            __name__,
                            template_folder='templates/speedreview')



@speedreview_blueprint.route('/game',methods=['GET','POST'])
@login_required
def game():
    cards = Card.query.all()
    return render_template('game.html',cards=cards)


# View for score screen (not currently implemented) #

@speedreview_blueprint.route('scorescreen',methods=['GET','POST'])
def scorescreen():
    form = request.form
    print(form[0])

    #print(type(cardid))
    # split = cardid.split(",")
    # idl = []
    # for item in split:
    #     idl.append(int(item))
    #
    # print(idl)

    return render_template('scorescreen.html')

# Old update view for updating a users score via a form #

# @speedreview_blueprint.route('updatescore',methods=['POST'])
# def updatescore():
#     form = request.form
#     cardid = int(form['cardid'])
#     userid = int(form['userid'])
#
#     update_score(userid,cardid)
#     print("success")
#     return ('', 204)
#
#

prota/speedreview/templates/speedreview/game.html
{% extends "base.html" %}
{% block content %}

<head>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/speedreview/game.css') }}">
</head>

<p class="flash-message hide-group">hello</p>
<div class="container all">
    <h2 class="text-center headers" id="title">English -> French</h2>
    <h1 class="text-center headers" id="question">Question</h1>
    <div class="container question-answers">
        <div class="row">
            <div class="col-md-6">
                <div class="row m-2">
                    <div class="col-md-12 qbox" id="btn1" onclick="check_answer('btn1')">

                    </div>
                </div>
                <div class="row m-2">
                    <div class="col-md-12 qbox" id="btn2" onclick="check_answer('btn2')">

                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="row m-2">
                    <div class="col-md-12 qbox" id="btn3" onclick="check_answer('btn3')">

                    </div>
                </div>
                <div class="row m-2">
                    <div class="col-md-12 qbox" id="btn4" onclick="check_answer('btn4')">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  <script type="text/javascript">
	  var items = [
		{% for item in cards %}
			{
			    id:"{{ item.id }}",
				sound:"{{item.fr_snd.split(',')[0]}}",
				fr:"{{item.fr}}",
				eng:"{{item.eng}}"
			},
		{% endfor %}
		];

	var maxcount = items.length;
	var count = 0;
	var answer = "";
	var cardidar = [];
	var wrong = 0;

	function genNum(limit){
		var arr = [];
		while(arr.length < 4){
    	var r = Math.floor(Math.random()*limit) + 1;
    	if(arr.indexOf(r) === -1) arr.push(r);
		}
		return arr;
	}

	function new_question(count) {
		question.innerHTML = items[count].eng;

		tmp = genNum(items.length-1);
		btn1.innerHTML = items[tmp[0]].fr;
		btn2.innerHTML = items[tmp[1]].fr;
		btn3.innerHTML = items[tmp[2]].fr;
		btn4.innerHTML = items[tmp[3]].fr;


		switch(genNum(4)[0]) {
			case 1:
			btn1.innerHTML = items[count].fr;
			answer = "btn1";
			break;
			case 2:
			btn2.innerHTML = items[count].fr ;
			answer = "btn2";
			break;
			case 3:
			btn3.innerHTML = items[count].fr;
			answer = "btn3";
			break;
			case 4:
			btn4.innerHTML = items[count].fr;
			answer = "btn4";
			break;

		}
	}

	function check_answer(choice) {
		if (choice == answer) {
		    updatescoreapi(items[count].id);
		    cardidar.push(items[count].id);
			if (count < maxcount) {
				count +=1;
				new_question(count);
			} else {
			    end()
            }
		} else {
            window.alert("Wrong!");
		    if (count < maxcount) {
                count += 1;
                new_question(count);
            } else {
		        end()
            }
		}
	}


	function end(){
	    window.alert("Youve Finished");
	    console.log(cardid);

        scoreValue = 20;
        var MY_URL = "{{ url_for("speedreview.scorescreen") }}";
        var xhr = new XMLHttpRequest();
        var data = new FormData();
        data.append('score', scoreValue);
        data.append('cardid',cardidar);
        xhr.open('POST', MY_URL);
        xhr.send(data);

    }

    {#function updatescore(cardid) {#}
    {#    var MY_URL = "{{ url_for("speedreview.updatescore") }}";#}
    {#    var xhr = new XMLHttpRequest();#}
    {#    var data = new FormData();#}
    {#    data.append('userid',{{ current_user.id }});#}
    {#    data.append('cardid',cardid);#}
    {#    xhr.open('POST', MY_URL);#}
    {#    xhr.send(data);#}

    {#  function updatescoreapi(cardid) {#}
    {#    var MY_URL = "{{ url_for("score/api.post") }}";#}
    {#    var xhr = new XMLHttpRequest();#}
    {#    var userid = "/{{ current_user.id }}/";#}
    {#    var url = MY_URL.concat(MY_URL,userid,cardid);#}
    {#    xhr.open('POST', MY_URL);#}
    {#    xhr.send(url);#}


    function updatescoreapi(cardid) {
	    var xhr = new XMLHttpRequest();
	    var MY_URL = "../score/api/score";
        xhr.open("POST", MY_URL, true);
        xhr.setRequestHeader('Content-Type', 'application/json');
        xhr.send(JSON.stringify({
            userid:{{ current_user.id }},
            cardid:cardid
        }))
	}
	function flash() {
        $(".flash-message").toggleClass("hide-group");
        $(".question-answers").toggleClass("hide-group");

        $(".flash-message").toggleClass("hide-group",function() {
            setTimeout(function() {
                $(".flash-message").toggleClass("hide-group");
            }, 5000)
        });

    }

	function flash3() {
        $(".flash-message").slideDown(function() {
            setTimeout(function() {
        $(".flash-message").slideUp();
            }, 5000);
            });

    }





	new_question(count);
  </script>
{% endblock %}

prota/speedreview/templates/speedreview/scorescreen.html
{% extends "base.html" %}
{% block content %}

    hello

    {{ cardid }}





{% endblock %}